# Generated by Django 3.2.6 on 2021-09-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image2',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
