# Generated by Django 3.2.6 on 2021-09-10 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_image_movie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image1',
            new_name='Sports',
        ),
    ]
